apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-re
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
